"""empty message

Revision ID: 06237af3925e
Revises: d216479c3a00
Create Date: 2017-03-25 01:27:13.994632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06237af3925e'
down_revision = 'd216479c3a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_date')
    # ### end Alembic commands ###
